//
//  SplashPresenter.swift
//  Rooted
//
//  Created by Michael Westbrooks on 5/17/20.
//  Copyright (c) 2020 RedRooster Technologies Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SplashPresentationLogic {
  func onNavigateToDashboard(response: Splash.CheckIfUserSessionExists.Response)
  func onNavigateToLogin(response: Splash.CheckIfUserSessionExists.Response)
  func onHandleError(response: Splash.HandleError.Response)
}

class SplashPresenter: SplashPresentationLogic {
  weak var viewController: SplashDisplayLogic?

  func onNavigateToDashboard(response: Splash.CheckIfUserSessionExists.Response) {
    var viewModel = Splash.CheckIfUserSessionExists.ViewModel()
    viewModel.userId = response.userId
    viewController?.doNavigateToDashboard(viewModel: viewModel)
  }

  func onNavigateToLogin(response: Splash.CheckIfUserSessionExists.Response) {
    let viewModel = Splash.CheckIfUserSessionExists.ViewModel()
    viewController?.doNavigateToDashboard(viewModel: viewModel)
  }

  func onHandleError(response: Splash.HandleError.Response) {
    var viewModel = Splash.HandleError.ViewModel()
    viewModel.error = response.error
    viewModel.errorMessage = response.errorMessage
    viewModel.errorTitle = response.errorTitle
    viewController?.handleError(viewModel: viewModel)
  }
}
