//
//  SplashInteractor.swift
//  Rooted
//
//  Created by Michael Westbrooks on 5/17/20.
//  Copyright (c) 2020 RedRooster Technologies Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SplashBusinessLogic {
  func checkIfUserSessionExists(request: Splash.CheckIfUserSessionExists.Request)
}

protocol SplashDataStore {
  var userId: String? { get set }
}

class SplashInteractor: SplashBusinessLogic, SplashDataStore {

  var presenter: SplashPresentationLogic?
  var sessionManager: SessionManager = SessionManager.shared

  var userId: String?

  // MARK: - Use Case: When app loads initial view, we want to check to see if a session exists for the user
  func checkIfUserSessionExists(request: Splash.CheckIfUserSessionExists.Request) {
    var response = Splash.CheckIfUserSessionExists.Response()
    if let userid = sessionManager.currentUserId {
      self.userId = userid

      response.userId = userid
      self.presenter?.onNavigateToDashboard(response: response)
    } else {
      self.presenter?.onNavigateToLogin(response: response)
    }
  }
}
