//
//  SplashRouter.swift
//  Rooted
//
//  Created by Michael Westbrooks on 5/17/20.
//  Copyright (c) 2020 RedRooster Technologies Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SplashRoutingLogic {
  func routeToDashboard()
  func routeToLogin()
}

protocol SplashDataPassing {
  var dataStore: SplashDataStore? { get }
}

class SplashRouter: NSObject, SplashRoutingLogic, SplashDataPassing {
  weak var viewController: SplashViewController?
  var dataStore: SplashDataStore?
  
  // MARK: - If user session exists due to the ability to derive a `User` object from business logic, go to the dashboard known as the `MyInvitesViewController` scene
  func routeToDashboard() {
    let storyboard = UIStoryboard(name: "Main", bundle: nil)
    let destinationVC = storyboard.instantiateViewController(withIdentifier: "MyInvitesViewController") as! MyInvitesViewController
    navigateToDashboard(source: viewController!, destination: destinationVC)
  }

  func navigateToDashboard(source: SplashViewController, destination: MyInvitesViewController) {
    source.show(destination, sender: nil)
  }

  // MARK: - If user session does not exist, go to the start the authentication process
  func routeToLogin() {
    let storyboard = UIStoryboard(name: "Main", bundle: nil)
    let destinationVC = storyboard.instantiateViewController(withIdentifier: "PhoneLoginViewController") as! PhoneLoginViewController
    navigateToLogin(source: viewController!, destination: destinationVC)
  }

  func navigateToLogin(source: SplashViewController, destination: PhoneLoginViewController) {
    source.show(destination, sender: nil)
  }
}
