//
//  EditProfileModels.swift
//  Rooted
//
//  Created by Michael Westbrooks on 7/31/20.
//  Copyright (c) 2020 RedRooster Technologies Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum EditProfile {
  // MARK: Use cases
  
  enum UpdateProfile {
    struct Request {
      var fullName: String?
      var phoneNumber: String?
      var companyName: String?
      var jobTitle: String?
      var emailAddress: String?
    }

    struct Response { }

    struct ViewModel { }
  }

  enum ForgotPassword {
    struct Request {
      var email: String!
    }

    struct Response {
      var emailSent: Bool!
    }

    struct ViewModel {
      var emailSent: Bool!
    }
  }

  enum HandleError {
    struct Request { }

    struct Response {
      var error: Error?
      var errorTitle: String?
      var errorMessage: String?
    }

    struct ViewModel {
      var error: Error?
      var errorTitle: String?
      var errorMessage: String?
    }
  }
}
