//
//  EditProfilePresenter.swift
//  Rooted
//
//  Created by Michael Westbrooks on 7/31/20.
//  Copyright (c) 2020 RedRooster Technologies Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EditProfilePresentationLogic {
  func onSuccessfulForgotPassword(response: EditProfile.ForgotPassword.Response)
  func handleError(response: EditProfile.HandleError.Response)
}

class EditProfilePresenter: EditProfilePresentationLogic {
  weak var viewController: EditProfileDisplayLogic?

  func onSuccessfulForgotPassword(response: EditProfile.ForgotPassword.Response) {
    var viewModel = EditProfile.ForgotPassword.ViewModel()
    viewModel.emailSent = response.emailSent
    viewController?.onSuccessfulForgotPassword(viewModel: viewModel)
  }

  func handleError(response: EditProfile.HandleError.Response) {
    var viewModel = EditProfile.HandleError.ViewModel()
    viewModel.error = response.error
    viewModel.errorMessage = response.errorMessage
    viewModel.errorTitle = response.errorTitle
    viewController?.handleError(viewModel: viewModel)
  }
}
