//
//  RegistrationPresenter.swift
//  Rooted
//
//  Created by Michael Westbrooks on 5/18/20.
//  Copyright (c) 2020 RedRooster Technologies Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RegistrationPresentationLogic {
  func onSuccessfulRegistration(response: Registration.RegisterViaEmailAndPassword.Response)
  func startUserSession(response: Registration.SetSession.Response)
  func handleError(response: Registration.HandleError.Response)
}

class RegistrationPresenter: RegistrationPresentationLogic {
  weak var viewController: RegistrationDisplayLogic?

  func onSuccessfulRegistration(response: Registration.RegisterViaEmailAndPassword.Response) {
    var viewModel = Registration.RegisterViaEmailAndPassword.ViewModel()
    viewModel.userId = response.userId
    viewModel.userData = response.userData
    viewController?.onSuccessfulRegistration(viewModel: viewModel)
  }

  func startUserSession(response: Registration.SetSession.Response) {
    var viewModel = Registration.SetSession.ViewModel()
    viewModel.userId = response.userId
    viewController?.onSuccessfulSessionSet(viewModel: viewModel)
  }

  func handleError(response: Registration.HandleError.Response) {
    var viewModel = Registration.HandleError.ViewModel()
    viewModel.error = response.error
    viewModel.errorMessage = response.errorMessage
    viewModel.errorTitle = response.errorTitle
    viewController?.handleError(viewModel: viewModel)
  }
}
