//
//  PhoneLoginPresenter.swift
//  Rooted
//
//  Created by Michael Westbrooks on 5/16/20.
//  Copyright (c) 2020 RedRooster Technologies Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PhoneLoginPresentationLogic {
}

class PhoneLoginPresenter: PhoneLoginPresentationLogic {
  weak var viewController: PhoneLoginDisplayLogic?
  
}
