//
//  PhoneLoginViewController.swift
//  Rooted
//
//  Created by Michael Westbrooks on 5/16/20.
//  Copyright (c) 2020 RedRooster Technologies Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PhoneLoginDisplayLogic: class {

  /// Handle any and all scenarios when something goes wrong
  func handleError(viewModel: PhoneLogin.HandleError.ViewModel)
}

class PhoneLoginViewController: BaseAppViewController, PhoneLoginDisplayLogic {
  var interactor: PhoneLoginBusinessLogic?
  var router: (NSObjectProtocol & PhoneLoginRoutingLogic & PhoneLoginDataPassing)?

  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder) {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  private func setup() {
    let viewController = self
    let interactor = PhoneLoginInteractor()
    let presenter = PhoneLoginPresenter()
    let router = PhoneLoginRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }

  // MARK: View lifecycle
  override func viewDidLoad() {
    super.viewDidLoad()
  }

}
