//
//  PhoneLoginInteractor.swift
//  Rooted
//
//  Created by Michael Westbrooks on 5/16/20.
//  Copyright (c) 2020 RedRooster Technologies Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PhoneLoginBusinessLogic {
  func loginViaEmailAndPassword(request: PhoneLogin.LoginViaEmailAndPassword.Request)
  func startUserSession(request: PhoneLogin.SetSession.Request)
  func forgotPassword(request: PhoneLogin.ForgotPassword.Request)
}

protocol PhoneLoginDataStore {
  var authenticationLogicDelegate: AuthenticationLogic? { get set }
}

class PhoneLoginInteractor: PhoneLoginBusinessLogic, PhoneLoginDataStore {
  var presenter: PhoneLoginPresentationLogic?
  var worker: PhoneLoginWorker?

  var authenticationLogicDelegate: AuthenticationLogic?
  
  // MARK: - Use Case: When a user provides their email address, try to log them in via Firebase
  func loginViaEmailAndPassword(request: PhoneLogin.LoginViaEmailAndPassword.Request) {
    guard let email = request.email, let password = request.password else {
      var error = PhoneLogin.HandleError.Response()
      error.errorMessage = "Please provide account credentials"
      error.errorTitle = "Oops!"
      self.presenter?.handleError(response: error)
      return
    }
    let path = PathBuilder.build(.Test, in: .Auth, with: "leo")
    let params: [String: String] = [
      "action": "email_login",
      "email": email,
      "password": password
    ]
    let apiService = Api()
    apiService.performRequest(path: path,
                              method: .post,
                              parameters: params) { (results, error) in

                                guard error == nil else {
                                  RRLogger.logError(message: "There was an error with the JSON.", owner: self, rError: .generalError)
                                  var error = PhoneLogin.HandleError.Response()
                                  error.errorMessage = "Something went wrong. Please try again."
                                  error.errorTitle = "Oops!"
                                  self.presenter?.handleError(response: error)
                                  return
                                }

                                guard let resultsDict = results as? [String: Any] else {
                                  RRLogger.logError(message: "There was an error with the JSON.", owner: self, rError: .generalError)
                                  var error = PhoneLogin.HandleError.Response()
                                  error.errorMessage = "Something went wrong. Please try again."
                                  error.errorTitle = "Oops!"
                                  self.presenter?.handleError(response: error)
                                  return
                                }

                                RRLogger.log(message: "Data was returned\n\nResults Dict: \(resultsDict)", owner: self)

                                if let success = resultsDict["success"] as? Bool {
                                  if success {
                                    if let data = resultsDict["data"] as? [String: Any] {
                                      var response = PhoneLogin.LoginViaEmailAndPassword.Response()
                                      response.userId = data["uid"] as? String ?? ""
                                      response.userData = UserProfileData(JSON: (data["user"] as? [[String: Any]])?.first ?? [:])
                                      self.presenter?.onSuccessfulEmailAndPasswordLogin(response: response)
                                    } else {
                                      var error = PhoneLogin.HandleError.Response()
                                      error.errorMessage = "Something went wrong. Please try again."
                                      error.errorTitle = "Oops!"
                                      self.presenter?.handleError(response: error)
                                    }
                                  } else {
                                    var error = PhoneLogin.HandleError.Response()
                                    error.errorMessage = resultsDict["error_message"] as? String ?? "Something went wrong. Please try again."
                                    error.errorTitle = "Oops!"
                                    self.presenter?.handleError(response: error)
                                  }
                                }
    }
  }

  func startUserSession(request: PhoneLogin.SetSession.Request) {
    if let userid = request.userId {
      var response = PhoneLogin.SetSession.Response()
      if let user = request.userData {
        SessionManager.start(with: user)
        response.userData = user
      } else {
        SessionManager.start(with: userid)
      }
      response.userId = userid
      self.presenter?.startUserSession(response: response)
    } else {
      var error = PhoneLogin.HandleError.Response()
      error.errorMessage = "Something went wrong. Please try again."
      error.errorTitle = "Oops!"
      self.presenter?.handleError(response: error)
    }
  }

  func forgotPassword(request: PhoneLogin.ForgotPassword.Request) {
    guard let email = request.email else {
      var error = PhoneLogin.HandleError.Response()
      error.errorMessage = "Please provide account credential"
      error.errorTitle = "Oops!"
      self.presenter?.handleError(response: error)
      return
    }
    let path = PathBuilder.build(.Test, in: .Auth, with: "leo")
    let params: [String: String] = [
      "action": "forgot_password",
      "email": email,
    ]
    let apiService = Api()
    apiService.performRequest(path: path,
                              method: .post,
                              parameters: params) { (results, error) in

                                guard error == nil else {
                                  RRLogger.logError(message: "There was an error with the JSON.", owner: self, rError: .generalError)
                                  var error = PhoneLogin.HandleError.Response()
                                  error.errorMessage = "Something went wrong. Please try again."
                                  error.errorTitle = "Oops!"
                                  self.presenter?.handleError(response: error)
                                  return
                                }

                                guard let resultsDict = results as? [String: Any] else {
                                  RRLogger.logError(message: "There was an error with the JSON.", owner: self, rError: .generalError)
                                  var error = PhoneLogin.HandleError.Response()
                                  error.errorMessage = "Something went wrong. Please try again."
                                  error.errorTitle = "Oops!"
                                  self.presenter?.handleError(response: error)
                                  return
                                }

                                RRLogger.log(message: "Data was returned\n\nResults Dict: \(resultsDict)", owner: self)

                                if let success = resultsDict["success"] as? Bool {
                                  if success {
                                    if let data = resultsDict["data"] as? [String: Any] {
                                      var response = PhoneLogin.ForgotPassword.Response()
                                      response.emailSent = data["email_sent"] as? Bool ?? false
                                      self.presenter?.onSuccessfulForgotPassword(response: response)
                                    } else {
                                      var error = PhoneLogin.HandleError.Response()
                                      error.errorMessage = "Something went wrong. Please try again."
                                      error.errorTitle = "Oops!"
                                      self.presenter?.handleError(response: error)
                                    }
                                  } else {
                                    var error = PhoneLogin.HandleError.Response()
                                    error.errorMessage = resultsDict["error_message"] as? String ?? "Something went wrong. Please try again."
                                    error.errorTitle = "Oops!"
                                    self.presenter?.handleError(response: error)
                                  }
                                }
    }
  }
}
