//
//  PhoneLoginPresenter.swift
//  Rooted
//
//  Created by Michael Westbrooks on 5/16/20.
//  Copyright (c) 2020 RedRooster Technologies Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PhoneLoginPresentationLogic {
  func onSuccessfulEmailAndPasswordLogin(response: PhoneLogin.LoginViaEmailAndPassword.Response)
  func onSuccessfulForgotPassword(response: PhoneLogin.ForgotPassword.Response)
  func startUserSession(response: PhoneLogin.SetSession.Response)
  func handleError(response: PhoneLogin.HandleError.Response)
}

class PhoneLoginPresenter: PhoneLoginPresentationLogic {
  weak var viewController: PhoneLoginDisplayLogic?

  func onSuccessfulEmailAndPasswordLogin(response: PhoneLogin.LoginViaEmailAndPassword.Response) {
    var viewModel = PhoneLogin.LoginViaEmailAndPassword.ViewModel()
    viewModel.userId = response.userId
    viewModel.userData = response.userData
    viewController?.onSuccessfulEmailAndPasswordLogin(viewModel: viewModel)
  }

  func onSuccessfulForgotPassword(response: PhoneLogin.ForgotPassword.Response) {
    var viewModel = PhoneLogin.ForgotPassword.ViewModel()
    viewModel.emailSent = response.emailSent
    viewController?.onSuccessfulForgotPassword(viewModel: viewModel)
  }

  func startUserSession(response: PhoneLogin.SetSession.Response) {
    var viewModel = PhoneLogin.SetSession.ViewModel()
    viewModel.userId = response.userId
    viewController?.onSuccessfulSessionSet(viewModel: viewModel)
  }

  func handleError(response: PhoneLogin.HandleError.Response) {
    var viewModel = PhoneLogin.HandleError.ViewModel()
    viewModel.error = response.error
    viewModel.errorMessage = response.errorMessage
    viewModel.errorTitle = response.errorTitle
    viewController?.handleError(viewModel: viewModel)
  }
}
