//
//  PhoneLoginViewController.swift
//  Rooted
//
//  Created by Michael Westbrooks on 5/16/20.
//  Copyright (c) 2020 RedRooster Technologies Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import OnboardKit

protocol AuthenticationLogic: class {
  func onSucessfulLogin(_ sender: PhoneLoginViewController, uid: String?)
  func handleFailedLogin(_ sender: PhoneLoginViewController, reason: String)
  func onSucessfulRegistration(_ sender: RegistrationViewController, uid: String?)
  func handleFailedRegistration(_ sender: RegistrationViewController, reason: String)
}

extension AuthenticationLogic {
  func onSucessfulLogin(_ sender: PhoneLoginViewController, uid: String?) { }
  func handleFailedLogin(_ sender: PhoneLoginViewController, reason: String) { }
  func onSucessfulRegistration(_ sender: RegistrationViewController, uid: String?) { }
  func handleFailedRegistration(_ sender: RegistrationViewController, reason: String) { }
}

protocol PhoneLoginDisplayLogic: class {
  func onSuccessfulEmailAndPasswordLogin(viewModel: PhoneLogin.LoginViaEmailAndPassword.ViewModel)
  func onSuccessfulForgotPassword(viewModel: PhoneLogin.ForgotPassword.ViewModel)
  func onSuccessfulSessionSet(viewModel: PhoneLogin.SetSession.ViewModel)

  /// Handle any and all scenarios when something goes wrong
  func handleError(viewModel: PhoneLogin.HandleError.ViewModel)
}

let kSubtitleSignInYourAccount = "Sign-in to your account"
let kSubtitleForgotYourPassword = "Forgot your password?"
let kButtonLogin = "Login"
let kButtonCancel = "Go back to Login"
let kButtonCreateNewPassword = "Create New Password"
let kButtonForgotPassword = kSubtitleForgotYourPassword

class PhoneLoginViewController: FormMessagesAppViewController, PhoneLoginDisplayLogic, UITextFieldDelegate {

  @IBOutlet var loginButton: UIButton!
  @IBOutlet weak var forgotPasswordButton: UIButton!
  @IBOutlet weak var subTitleLabel: UILabel!

  var interactor: PhoneLoginBusinessLogic?
  var router: (NSObjectProtocol & PhoneLoginRoutingLogic & PhoneLoginDataPassing)?

  var isLogin: Bool! {
    didSet {
      self.form.removeAll()
      switch self.isLogin {
      case true:
        self.subTitleLabel.text = kSubtitleSignInYourAccount
        self.forgotPasswordButton.setTitle(kButtonForgotPassword, for: .normal)
        self.loginButton.setTitle(kButtonLogin, for: .normal)
        self.loadForm()
      case false:
        self.subTitleLabel.text = kSubtitleForgotYourPassword
        self.forgotPasswordButton.setTitle(kButtonCancel, for: .normal)
        self.loginButton.setTitle(kButtonCreateNewPassword, for: .normal)
        self.loadForm()
      case .none, .some(_):
        break
      }
    }
  }

  // MARK: Object lifecycle
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder) {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  private func setup() {
    let viewController = self
    let interactor = PhoneLoginInteractor()
    let presenter = PhoneLoginPresenter()
    let router = PhoneLoginRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }

  // MARK: View lifecycle
  override func viewDidLoad() {
    super.viewDidLoad()
    loginButton.applyCornerRadius()
    isLogin = true
  }

  func loadForm() {
    self.tableView.separatorStyle = UITableViewCell.SeparatorStyle.none

    form +++ Section()
    <<< EmailRow(kFormEmailAddress) {
      $0.placeholder = kFormEmailPlaceholder
      $0.add(rule: RuleRequired())
      $0.add(rule: RuleEmail())
      $0.validationOptions = .validatesAlways

      if isDebug {
        $0.value = kDebugEmail
      }
    }.cellUpdate { cell, row in
      NavigationCoordinator.performExpandedNavigation(from: self) {
        // Adjust view
        if !row.isValid {
          cell.textField.textColor = .systemRed
          self.loginButton.isEnabled = false
          self.loginButton.isUserInteractionEnabled = false
        } else {
          cell.textField.textColor = .black
          self.loginButton.isEnabled = true
          self.loginButton.isUserInteractionEnabled = true
        }
      }
    }

    if isLogin {
      form.last! <<< PasswordRow(kFormPassword) {
        $0.placeholder = kFormPasswordPlaceholder
        $0.add(rule: RuleRequired())
        $0.validationOptions = .validatesAlways

        if isDebug {
          $0.value = kDebugPassword
        }

      }.cellUpdate { cell, row in
        NavigationCoordinator.performExpandedNavigation(from: self) {
          // Adjust view
          if !row.isValid {
            cell.textField.textColor = .systemRed
            self.loginButton.isEnabled = false
            self.loginButton.isUserInteractionEnabled = false
          } else {
            cell.textField.textColor = .black
            self.loginButton.isEnabled = true
            self.loginButton.isUserInteractionEnabled = true
          }
        }
      }
    }
  }

  @IBAction func loginAction(_ sender: UIButton) {
    if isLogin {
      self.loginViaEmailAndPassword()
    } else {
      self.forgotPassword()
    }
  }

  // MARK: - Use Case: When a user forgets their password, send a request to retrieve new password
  @IBAction func forgotPasswordAction(_ sender: UIButton) {
    // Update UI
    if isLogin {
      isLogin = false
    } else {
      isLogin = true
    }
  }

  func forgotPassword() {
    showHUD()
    var request = PhoneLogin.ForgotPassword.Request()
    request.email = (form.rowBy(tag: kFormEmailAddress) as? EmailRow)?.value ?? ""
    interactor?.forgotPassword(request: request)
  }

  func onSuccessfulForgotPassword(viewModel: PhoneLogin.ForgotPassword.ViewModel) {
    dismissHUD()
    displayError(with: "Forgot Password", and: "Successfully requested a new password.")
    isLogin = true
  }

  // MARK: - Use Case: When a user provides their email and a password, try to log them in via Firebase
  func loginViaEmailAndPassword() {
    showHUD()
    var request = PhoneLogin.LoginViaEmailAndPassword.Request()
    request.email = (form.rowBy(tag: kFormEmailAddress) as? EmailRow)?.value ?? ""
    request.password = (form.rowBy(tag: kFormPassword) as? PasswordRow)?.value ?? ""
    interactor?.loginViaEmailAndPassword(request: request)
  }

  func onSuccessfulEmailAndPasswordLogin(viewModel: PhoneLogin.LoginViaEmailAndPassword.ViewModel) {
    dismissHUD()
    startUserSession(with: viewModel.userId, and: viewModel.userData)
  }

  func startUserSession(with userId: String?, and userData: UserProfileData?) {
    var request = PhoneLogin.SetSession.Request()
    request.userId = userId
    request.userData = userData
    interactor?.startUserSession(request: request)
  }

  func onSuccessfulSessionSet(viewModel: PhoneLogin.SetSession.ViewModel) {
    let _ = SweetAlert().showAlert(on: self, title: "Thank You!", subTitle: "You are now logged in.", style: .success, buttonTitle: "Proceed", buttonColor: .systemOrange) { success in
      self.dismiss(animated: true, completion: {
        self.router?.dataStore?.authenticationLogicDelegate?.onSucessfulLogin(self, uid: viewModel.userId)
      })
    }
  }

  func handleError(viewModel: PhoneLogin.HandleError.ViewModel) {
    dismissHUD()
    let _ = SweetAlert().showAlert(on: self,
                                   title: viewModel.errorTitle ?? "Oops",
                                   subTitle: viewModel.errorMessage ?? "Something went wrong. Please try again.",
                                   style: .error,
                                   buttonTitle: "OK",
                                   buttonColor: .systemOrange)
  }
}

// Reusable components
extension PhoneLoginViewController {
  // MARK: - Use Case: Show ProgressHUD
  func showHUD() {
    DispatchQueue.main.async {
      self.progressHUD?.show()
    }
  }

  // MARK: - Use Case: Dismiss ProgressHUD
  func dismissHUD() {
    DispatchQueue.main.async {
      self.progressHUD?.dismiss()
    }
  }
}
