//
//  PhoneLoginRouter.swift
//  Rooted
//
//  Created by Michael Westbrooks on 5/16/20.
//  Copyright (c) 2020 RedRooster Technologies Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol PhoneLoginRoutingLogic {
  func routeToCreateAnAccount()
}

protocol PhoneLoginDataPassing {
  var dataStore: PhoneLoginDataStore? { get }
}

class PhoneLoginRouter: NSObject, PhoneLoginRoutingLogic, PhoneLoginDataPassing {
  weak var viewController: PhoneLoginViewController?
  var dataStore: PhoneLoginDataStore?
  
  // MARK: Routing
  func routeToCreateAnAccount() {
    let storyboard = UIStoryboard(name: kStoryboardMain, bundle: nil)
    let destinationVC = storyboard.instantiateViewController(withIdentifier: kRegistrationViewController) as! RegistrationViewController
    navigateToCreateAnAccount(source: viewController!, destination: destinationVC)
  }

  func navigateToCreateAnAccount(source: PhoneLoginViewController, destination: RegistrationViewController) {
    source.present(destination, animated: true, completion: nil)
  }
}
