//
//  ForgotPasswordInteractor.swift
//  Rooted
//
//  Created by Michael Westbrooks on 6/20/20.
//  Copyright (c) 2020 RedRooster Technologies Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ForgotPasswordBusinessLogic
{
  func doSomething(request: ForgotPassword.Something.Request)
}

protocol ForgotPasswordDataStore
{
  //var name: String { get set }
}

class ForgotPasswordInteractor: ForgotPasswordBusinessLogic, ForgotPasswordDataStore
{
  var presenter: ForgotPasswordPresentationLogic?
  var worker: ForgotPasswordWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: ForgotPassword.Something.Request)
  {
    worker = ForgotPasswordWorker()
    worker?.doSomeWork()
    
    let response = ForgotPassword.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
