//
//  PhoneVerificationPresenter.swift
//  Rooted
//
//  Created by Michael Westbrooks on 7/23/20.
//  Copyright (c) 2020 RedRooster Technologies Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PhoneVerificationPresentationLogic
{
  func presentSomething(response: PhoneVerification.Something.Response)
}

class PhoneVerificationPresenter: PhoneVerificationPresentationLogic
{
  weak var viewController: PhoneVerificationDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: PhoneVerification.Something.Response)
  {
    let viewModel = PhoneVerification.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
