//
//  PhoneVerificationInteractor.swift
//  Rooted
//
//  Created by Michael Westbrooks on 7/23/20.
//  Copyright (c) 2020 RedRooster Technologies Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PhoneVerificationBusinessLogic
{
  func doSomething(request: PhoneVerification.Something.Request)
}

protocol PhoneVerificationDataStore
{
  //var name: String { get set }
}

class PhoneVerificationInteractor: PhoneVerificationBusinessLogic, PhoneVerificationDataStore
{
  var presenter: PhoneVerificationPresentationLogic?
  var worker: PhoneVerificationWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: PhoneVerification.Something.Request)
  {
    worker = PhoneVerificationWorker()
    worker?.doSomeWork()
    
    let response = PhoneVerification.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
