//
//  PhoneVerificationViewController.swift
//  Rooted
//
//  Created by Michael Westbrooks on 7/23/20.
//  Copyright (c) 2020 RedRooster Technologies Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PhoneVerificationDisplayLogic: class {
  func displaySomething(viewModel: PhoneVerification.Something.ViewModel)
}

class PhoneVerificationViewController: UIViewController, PhoneVerificationDisplayLogic {

  @IBOutlet weak var verificationCodeTextField: UITextField!
  @IBOutlet weak var resendCodeButton: UIButton!
  @IBOutlet weak var verifyPhoneNumberButton: UIButton!

  var interactor: PhoneVerificationBusinessLogic?
  var router: (NSObjectProtocol & PhoneVerificationRoutingLogic & PhoneVerificationDataPassing)?

  // MARK: - Lifecycle methods
  static func setupViewController() -> PhoneVerificationViewController {
    let storyboard = UIStoryboard(name: kStoryboardMain, bundle: nil)
    let viewController = storyboard.instantiateViewController(withIdentifier: "PhoneVerificationViewController") as! PhoneVerificationViewController
    return viewController
  }
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder) {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  private func setup() {
    let viewController = self
    let interactor = PhoneVerificationInteractor()
    let presenter = PhoneVerificationPresenter()
    let router = PhoneVerificationRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    doSomething()
  }
  
  // MARK: Do something
  
  //@IBOutlet weak var nameTextField: UITextField!
  
  func doSomething()
  {
    let request = PhoneVerification.Something.Request()
    interactor?.doSomething(request: request)
  }
  
  func displaySomething(viewModel: PhoneVerification.Something.ViewModel)
  {
    //nameTextField.text = viewModel.name
  }
}
