//
//  ViewCalendarPresenter.swift
//  Rooted
//
//  Created by Michael Westbrooks on 7/17/20.
//  Copyright (c) 2020 RedRooster Technologies Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ViewCalendarPresentationLogic {
}

class ViewCalendarPresenter: ViewCalendarPresentationLogic {
  weak var viewController: ViewCalendarDisplayLogic?
  
}
