//
//  ViewCalendarPresenter.swift
//  Rooted
//
//  Created by Michael Westbrooks on 7/17/20.
//  Copyright (c) 2020 RedRooster Technologies Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ViewCalendarPresentationLogic
{
  func presentSomething(response: ViewCalendar.Something.Response)
}

class ViewCalendarPresenter: ViewCalendarPresentationLogic
{
  weak var viewController: ViewCalendarDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: ViewCalendar.Something.Response)
  {
    let viewModel = ViewCalendar.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
