//
//  ViewCalendarRouter.swift
//  Rooted
//
//  Created by Michael Westbrooks on 7/17/20.
//  Copyright (c) 2020 RedRooster Technologies Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ViewCalendarRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol ViewCalendarDataPassing
{
  var dataStore: ViewCalendarDataStore? { get }
}

class ViewCalendarRouter: NSObject, ViewCalendarRoutingLogic, ViewCalendarDataPassing
{
  weak var viewController: ViewCalendarViewController?
  var dataStore: ViewCalendarDataStore?
  
  // MARK: Routing
  
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  // MARK: Navigation
  
  //func navigateToSomewhere(source: ViewCalendarViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: ViewCalendarDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
