
//
//  ViewCalendarInteractor.swift
//  Rooted
//
//  Created by Michael Westbrooks on 7/17/20.
//  Copyright (c) 2020 RedRooster Technologies Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ViewCalendarBusinessLogic
{
  func doSomething(request: ViewCalendar.Something.Request)
}

protocol ViewCalendarDataStore
{
  //var name: String { get set }
}

class ViewCalendarInteractor: ViewCalendarBusinessLogic, ViewCalendarDataStore
{
  var presenter: ViewCalendarPresentationLogic?
  var worker: ViewCalendarWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: ViewCalendar.Something.Request)
  {
    worker = ViewCalendarWorker()
    worker?.doSomeWork()
    
    let response = ViewCalendar.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
