//
//  ChatInteractor.swift
//  Rooted
//
//  Created by Michael Westbrooks on 6/1/20.
//  Copyright (c) 2020 RedRooster Technologies Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChatBusinessLogic
{
  func doSomething(request: Chat.Something.Request)
}

protocol ChatDataStore
{
  //var name: String { get set }
}

class ChatInteractor: ChatBusinessLogic, ChatDataStore
{
  var presenter: ChatPresentationLogic?
  var worker: ChatWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Chat.Something.Request)
  {
    worker = ChatWorker()
    worker?.doSomeWork()
    
    let response = Chat.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
