//
//  SettingsPresenter.swift
//  Rooted
//
//  Created by Michael Westbrooks on 5/23/20.
//  Copyright (c) 2020 RedRooster Technologies Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SettingsPresentationLogic {
  func onSuccessfullLogout(response: Settings.LogoutUser.Response)
  func onFailedLogout(response: Settings.LogoutUser.Response)
  func handleError(response: Settings.DisplayError.Response)
}

class SettingsPresenter: SettingsPresentationLogic {
  weak var viewController: SettingsDisplayLogic?

  func onSuccessfullLogout(response: Settings.LogoutUser.Response) {
    let viewModel = Settings.LogoutUser.ViewModel()
    viewController?.onSuccessfullLogout(viewModel: viewModel)
  }
  func onFailedLogout(response: Settings.LogoutUser.Response) {
    var viewModel = Settings.LogoutUser.ViewModel()
    viewModel.errorMessage = response.errorMessage
    viewController?.onFailedLogout(viewModel: viewModel)
  }

  func handleError(response: Settings.DisplayError.Response) {
    var viewModel = Settings.DisplayError.ViewModel()
    viewModel.errorTitle = response.errorTitle
    viewModel.errorMessage = response.errorMessage
    viewController?.handleError(viewModel: viewModel)
  }
}
