//
//  SettingsModels.swift
//  Rooted
//
//  Created by Michael Westbrooks on 5/23/20.
//  Copyright (c) 2020 RedRooster Technologies Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Settings {

  // MARK: - Use Case: A user wants to logout
  enum LogoutUser {
    struct Request {

    }

    struct Response {
      var errorMessage: String = ""
    }

    struct ViewModel {
      var errorMessage: String = ""
    }
  }

  enum DisplayError {
    struct Request { }

    struct Response {
      var errorTitle: String = ""
      var errorMessage: String = ""
    }

    struct ViewModel {
      var errorTitle: String = ""
      var errorMessage: String = ""
    }
  }
}
