//
//  UpdateValueModels.swift
//  Rooted
//
//  Created by Michael Westbrooks on 7/31/20.
//  Copyright (c) 2020 RedRooster Technologies Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum UpdateValue {
  // MARK: Use cases
  enum Something {
    struct Request {
      var tag: String!
      var value: String!
    }

    struct Response {
      var success: Bool?
      var userId: String?
      var userData: UserProfileData?
      var publicKey: String?
      var privateKey: String?
    }

    struct ViewModel {
      var success: Bool?
      var userId: String?
      var userData: UserProfileData?
      var publicKey: String?
      var privateKey: String?
    }
  }

  enum HandleError {
    struct Request { }

    struct Response {
      var error: Error?
      var errorTitle: String?
      var errorMessage: String?
    }

    struct ViewModel {
      var error: Error?
      var errorTitle: String?
      var errorMessage: String?
    }
  }
}
