//
//  UpdateValuePresenter.swift
//  Rooted
//
//  Created by Michael Westbrooks on 7/31/20.
//  Copyright (c) 2020 RedRooster Technologies Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol UpdateValuePresentationLogic {
  func onUpdateProfile(response: UpdateValue.Something.Response)
  /// Handle any and all scenarios when something goes wrong
  func handleError(response: UpdateValue.HandleError.Response)
}

class UpdateValuePresenter: UpdateValuePresentationLogic {
  weak var viewController: UpdateValueDisplayLogic?
  
  func onUpdateProfile(response: UpdateValue.Something.Response) {
    var viewModel = UpdateValue.Something.ViewModel()
    viewModel.userId = response.userId
    viewModel.userData = response.userData
    viewController?.onUpdateProfile(viewModel: viewModel)
  }

  func handleError(response: UpdateValue.HandleError.Response) {
    var viewModel = UpdateValue.HandleError.ViewModel()
    viewModel.error = response.error
    viewModel.errorMessage = response.errorMessage
    viewModel.errorTitle = response.errorTitle
    viewController?.handleError(viewModel: viewModel)
  }
}
